### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by gouravkhunger** [gouravkhunger/TextRecognizer#1]
This is a basic Java project and it can be easily converted to Kotlin.

Do upgrade the dependencies in the `build.gradle` file as they might have become old since the first release of the project.

**Comment by pratik9315** [comment]
Hello can i work on this issue?

**Comment by gouravkhunger** [comment]
Yeah sure! You can convert the project to Kotlin. I should inform you that this doesn't app use the MVVM structure for now. Just convert the splash screen and the main file to Kotlin and change the dependencies to kotlin ones. Migrating to the MVVM pattern would be a task for another time :)
